"""领域端口(Protocol 接口)。infra 实现它们,service 依赖它们 —— 依赖倒置。"""
from __future__ import annotations
from typing import Protocol, Optional
from app.domain.models import MaterialCandidate, Material, User


class VideoParser(Protocol):
    """反解智能体端口(Qwen-VL 的抽象)。"""
    def parse_video(self, oss_key: str) -> list[MaterialCandidate]: ...


class Embedder(Protocol):
    """物料 multimodal-embedding 端口。"""
    def embed(self, candidate: MaterialCandidate) -> list[float]: ...


class QueryEmbedder(Protocol):
    """查询文本 embedding 端口(搜索用)。"""
    def embed_text(self, text: str) -> list[float]: ...


class Auditor(Protocol):
    """内容安全审核端口。返回 'pass'/'review'/'block';可抛 TimeoutError。content 可为候选或物料。"""
    def audit(self, content) -> str: ...


class MaterialRepo(Protocol):
    """物料仓储端口。"""
    def save(self, material: Material) -> None: ...
    def get(self, material_id: str) -> Optional[Material]: ...
    def delete(self, material_id: str) -> None: ...
    def list(self) -> list[Material]: ...
    def search(self, query_text: str, only_pass: bool = True) -> list[Material]: ...


class ObjectStorage(Protocol):
    """OSS 存储端口。"""
    def put(self, oss_key: str, data: bytes) -> None: ...
    def signed_url(self, oss_key: str) -> str: ...
    def exists(self, oss_key: str) -> bool: ...
    def delete(self, oss_key: str) -> None: ...


class VectorIndex(Protocol):
    """向量索引端口(pgvector HNSW 的抽象)。"""
    def add(self, material_id: str, vector: list[float]) -> None: ...
    def query(self, vector: list[float], k: int = 10) -> list[str]: ...
    def size(self) -> int: ...


class UserRepo(Protocol):
    def save(self, user: User) -> None: ...
    def get_by_name(self, name: str) -> Optional[User]: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, pwd_hash: str) -> bool: ...


class TokenIssuer(Protocol):
    def issue(self, user_id: str) -> str: ...   # 返回含过期信息的 token


class RbacRepo(Protocol):
    def permissions_of(self, role: str) -> set[str]: ...
    def grant(self, role: str, permission: str) -> None: ...
    def revoke(self, role: str, permission: str) -> None: ...


class AuditLog(Protocol):
    def record(self, event: str) -> None: ...
