"""领域端口(Protocol 接口)。infra 实现它们,service 依赖它们 —— 依赖倒置。"""
from __future__ import annotations
from typing import Protocol, Optional
from app.domain.models import MaterialCandidate, Material, User, TextSegment, AuditRule, AuditTask, Project, TrainingSet, TrainingExample
from app.domain.query import MaterialQuery


class VideoParser(Protocol):
    """反解智能体端口(Qwen-VL 的抽象)。"""
    def parse_video(self, oss_key: str) -> list[MaterialCandidate]: ...


class Transcriber(Protocol):
    """语音转写端口(ASR,paraformer 的抽象)。输入媒体 URL → 带时间轴的转写段。"""
    def transcribe(self, url: str) -> list[TextSegment]: ...


class VisionDescriber(Protocol):
    """图像反解端口(Qwen-VL):把图片/关键帧解析成画面内容文字。"""
    def describe_image(self, url: str, hints: str = "") -> str: ...


class Llm(Protocol):
    """通用大模型端口(qwen-plus,JSON 输出)。供「挑重点时间段」与「规则判定」复用。"""
    def chat_json(self, system: str, user: str) -> dict: ...


class ArchiveTagger(Protocol):
    """物料档案端口(豆包 pro 2.1):看图片/整段视频 → 提可复用检索档案。
    返回 {summary, emotions:[], scenarios:[], atmosphere, tags:[]};失败返回 {} 不阻塞。"""
    def tag(self, material_type: str, media_url: str = "", is_video: bool = False,
            text: str = "") -> dict: ...


class WebSearcher(Protocol):
    """联网搜索端口(Tavily):按查询联网搜,返回拼好的简报文本(概述 + 结果摘要)。
    供音乐物料按歌名搜情绪/场景;失败(网络/超时)返回 "" 不阻塞。"""
    def search(self, query: str) -> str: ...


class AuditRuleRepo(Protocol):
    """审核规则仓储。by=操作人 id(PG 实现写 create_by/update_by;JSON/内存实现忽略)。"""
    def add(self, rule: AuditRule, by: str = "") -> None: ...
    def delete(self, rule_id: str, by: str = "") -> None: ...
    def list(self) -> list[AuditRule]: ...
    def list_for(self, source_type: str, project_id: str = "") -> list[AuditRule]: ...   # 全局规则 ∪ 该项目规则


class ProjectRepo(Protocol):
    """作品项目仓储(每个项目一组审核规则)。"""
    def add(self, project: Project) -> None: ...
    def get(self, project_id: str) -> Optional[Project]: ...
    def get_by_name(self, name: str) -> Optional[Project]: ...
    def delete(self, project_id: str) -> None: ...
    def list(self) -> list[Project]: ...


class AuditTaskRepo(Protocol):
    """待审核任务仓储(持久化,支撑「待审核」页)。"""
    def save(self, task: AuditTask) -> None: ...        # 新增或更新(状态回写)
    def get(self, task_id: str) -> Optional[AuditTask]: ...
    def delete(self, task_id: str) -> None: ...
    def list_for(self, owner_id: str, project_id: str = "", name: str = "", offset: int = 0, limit: int | None = None) -> list[AuditTask]: ...
    def list_all(self, project_id: str = "", name: str = "", offset: int = 0, limit: int | None = None) -> list[AuditTask]: ...
    def count_for(self, owner_id: str, project_id: str = "", name: str = "") -> int: ...
    def count_all(self, project_id: str = "", name: str = "") -> int: ...


class Embedder(Protocol):
    """物料 multimodal-embedding 端口。"""
    def embed(self, candidate: MaterialCandidate) -> list[float]: ...


class QueryEmbedder(Protocol):
    """查询文本 embedding 端口(搜索用)。"""
    def embed_text(self, text: str) -> list[float]: ...


class Auditor(Protocol):
    """内容安全审核端口。返回 'pass'/'review'/'block';可抛 TimeoutError。content 可为候选或物料。
    可选实现 audit_detail(content) -> (verdict, risk_words):额外交出阿里云命中的具体风险词
    (供报告标红 + 一键加白);未实现时调用方用 getattr 兜底为 (audit(content), '')。"""
    def audit(self, content) -> str: ...


class MaterialRepo(Protocol):
    """物料仓储端口。"""
    def save(self, material: Material) -> None: ...
    def get(self, material_id: str) -> Optional[Material]: ...
    def delete(self, material_id: str) -> None: ...
    def list(self) -> list[Material]: ...
    def search(self, query_text: str, only_pass: bool = True) -> list[Material]: ...
    def query(self, spec: MaterialQuery) -> tuple[list[Material], int]: ...  # 服务端翻页/筛选 →(当页, 总数)
    def by_content_hash(self, owner_id: str, content_hash: str) -> Optional[Material]: ...  # 同 owner 库内去重


class ObjectStorage(Protocol):
    """OSS 存储端口。"""
    def put(self, oss_key: str, data: bytes) -> None: ...
    def put_fileobj(self, oss_key: str, fileobj) -> None: ...   # 流式上传(file-like object)
    def signed_url(self, oss_key: str) -> str: ...          # 预览用签名 URL
    def download_url(self, oss_key: str) -> str: ...        # 下载用签名 URL(强制 attachment)
    def snapshot_url(self, oss_key: str, ms: int = 1000) -> str: ...  # 视频封面帧签名 URL
    def video_duration_ms(self, oss_key: str): ...                    # 视频时长(ms),拿不到→None
    def exists(self, oss_key: str) -> bool: ...
    def delete(self, oss_key: str) -> None: ...


class VectorIndex(Protocol):
    """向量索引端口(pgvector HNSW 的抽象)。"""
    def add(self, material_id: str, vector: list[float]) -> None: ...
    def query(self, vector: list[float], k: int = 10) -> list[str]: ...
    def query_scored(self, vector: list[float], k: int = 10) -> list[tuple[str, float]]: ...  # (id, 余弦距离);用于按相关度阈值过滤
    def size(self) -> int: ...


class UserRepo(Protocol):
    def save(self, user: User) -> None: ...
    def get_by_name(self, name: str) -> Optional[User]: ...
    def get(self, user_id: str) -> Optional[User]: ...
    def list(self) -> list[User]: ...               # 账号管理:列全部用户
    def delete(self, user_id: str) -> None: ...      # 账号管理:删用户


class FavoriteRepo(Protocol):
    """用户收藏关系(把公共物料收进自己的物料库)。"""
    def add(self, user_id: str, material_id: str) -> None: ...
    def remove(self, user_id: str, material_id: str) -> None: ...
    def material_ids(self, user_id: str) -> set[str]: ...
    def has(self, user_id: str, material_id: str) -> bool: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, pwd_hash: str) -> bool: ...


class TokenIssuer(Protocol):
    def issue(self, user_id: str) -> str: ...          # 签发带签名+过期的 token
    def verify(self, token: str) -> Optional[str]: ...  # 校验签名与有效期,返回 uid;无效→None


class RbacRepo(Protocol):
    def permissions_of(self, role: str) -> set[str]: ...
    def grant(self, role: str, permission: str) -> None: ...
    def revoke(self, role: str, permission: str) -> None: ...
    # 按用户授权(在角色默认权限之上叠加):功能权限页给具体用户授权
    def user_permissions(self, user_id: str) -> set[str]: ...
    def set_user_permissions(self, user_id: str, permissions: set[str]) -> None: ...


class AuditLog(Protocol):
    def record(self, event: str) -> None: ...


class WhitelistRepo(Protocol):
    """内容安全白名单:命中这些词时,即便阿里云判违规也放行(管理员后台维护,治误伤)。"""
    def words(self) -> set[str]: ...
    def list(self) -> list[str]: ...
    def add(self, word: str) -> None: ...
    def remove(self, word: str) -> None: ...


class BlockwordRepo(Protocol):
    """绝对禁词:管理员精选、非常确定不能出现的硬词(如特定政治/黄暴词)。
    审核第一波——命中任一即直接拦截(block),短路后续。因人工精选、量小,子串匹配可接受。"""
    def words(self) -> set[str]: ...
    def list(self) -> list[str]: ...
    def add(self, word: str) -> None: ...
    def remove(self, word: str) -> None: ...


class TrainingSetRepo(Protocol):
    """规则训练集仓储。"""
    def add(self, ts: TrainingSet, by: str = "") -> None: ...
    def get(self, ts_id: str) -> Optional[TrainingSet]: ...
    def get_by_project(self, project_id: str) -> Optional[TrainingSet]: ...
    def delete(self, ts_id: str, by: str = "") -> None: ...
    def list(self) -> list[TrainingSet]: ...


class TrainingExampleRepo(Protocol):
    """规则训练样本仓储。"""
    def add(self, te: TrainingExample, by: str = "") -> None: ...
    def get(self, te_id: str) -> Optional[TrainingExample]: ...
    def delete(self, te_id: str, by: str = "") -> None: ...
    def list_for_set(self, training_set_id: str) -> list[TrainingExample]: ...
